### ISSUE TITLE
makenetlist path finding issue

### ISSUE THREAD

**Issue by sebas-bouw** [Lenty/SLiCAP_python#19]
could not open the correct ltspice file, 
the extension is not "asc" 
i am a windows 10 user, the path dash is different than Linux \ /

![image](https://user-images.githubusercontent.com/73284560/96859286-9a6ab600-1461-11eb-9e3e-0fb8f132fd2e.png)

**Comment by sebas-bouw** [comment]
found issue, 
if there is only "xx.asc" file name the make netlist does not work,  
but if you run ltspice--> view--> spice Netlist, and then close the window, is does work. 

but does not generate a new netlist on its own 
(ltspice XVII(x64)

**Comment by Lenty** [comment]
While it is maybe not directly causing the issue, I have altered the filename to use os.path.abspath() which should make it more robust across different operating systems.
In addition, I have moved from the os.system to subprocess.run in order to be more robust in the makeNetlist command.

Does the issue persist if you update your SLiCAP installation?

**Comment by sebas-bouw** [comment]
what is the easiest way to update the slicap installation

**Comment by Lenty** [comment]
Either do:

- `git pull` 

Or download the zip from the master by:

- Going to https://github.com/Lenty/SLiCAP_python
- Pressing 'code'
- Clicking 'download zip' and extracting the zip.

In the SLiCAP_python directory then run: `python setup.py install --user` or `python setup.py install` depending on whether you want to do a local installation of an installation for everyone.

If anything is unclear please do not hesistate to ask for clarification!
