### ISSUE TITLE
Help() has no effect in Jupyter Notebook

### ISSUE THREAD

**Issue by ArthurAdmiraal** [Lenty/SLiCAP_python#23]
Hi! I am running:
``` python
from SLiCAP import *
my_project = initProject('my_firstSLiCAP_project')
Help()
```
But don't see the webpage mentioned in (the documentation)[https://analog-electronics.eu/slicap/SLiCAP_python/docs/html/userguide/install.html#getting-help] opening up with Firefox on OS X and Python 3.9. Have you run into this before?

**Comment by Lenty** [comment]
Hi! I have ran it locally on my Fedora 33 install with python 3.8.3. For me it works as designed (it opens the local 'help' web page):
![image](https://user-images.githubusercontent.com/4511638/98844536-bd7afb00-244c-11eb-813f-c9cf6de8c83b.png)

Could you check in the SLiCAP_python/SLiCAP/SLiCAPsettings/SLiCAPsettings.py what is defined as DOCPATH?

**Comment by Lenty** [comment]
Hmm, this looks like somewhere incorrect quotes are added or perhaps the not escaped space is causing some errors. I do not have a mac to try to debug it myself. However, what could be an option is to open an ipython console and run the following (with the path to your documentation):
![image](https://user-images.githubusercontent.com/4511638/98988880-9265d980-2528-11eb-8caa-a43b7d4b469e.png)
You can also rerun the installer and I believe it should remove the space (otherwise there is likely a bug in the installer).

**Comment by ArthurAdmiraal** [comment]
I just reran the installer with 1.0.1, and can confirm that the space and escaped space were due to user error. No luck with `webbrowser.open_new` though, although it does return `True`.
